version: '3.9'
services:
  db:
    image: postgres:13-alpine
    container_name: mhnu-postgres
    env_file: ./backend/.env
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  backend: &backend
    build: ./backend
    container_name: mhnu-backend
    command: [ "gunicorn", "mhnu.wsgi:application", "-b",  "0.0.0.0:8000", "-w", "3" ]
    env_file: ./backend/.env
    volumes:
      - ./backend:/backend
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=mhnu.settings.prod
    ports:
      - '8000:8000'

  frontend:
    build: ./frontend
    container_name: mhnu-frontend
    ports:
      - '3000:3000'

  redis:
    image: 'redis:alpine'
    container_name: mhnu-redis
    restart: always
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    ports:
      - '6379:6379'

  worker:
    <<: *backend
    container_name: mhnu-worker
    command: ["celery", "-A", "mhnu", "worker", "-B", "-l", "info"]
    depends_on:
      - redis
      - db
    ports: []
    restart: always

volumes:
  postgres-data: