version: '3.9'
services:
  db:
    image: postgres:13-alpine
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build: ./backend
    command: ["wait-for-it", "db:5432", "--", "gunicorn", "MHNU.wsgi:application", "--bind",  "0.0.0.0:8000"]
    env_file: .env
    volumes:
      - ./backend:/backend
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=MHNU.settings.prod
    ports:
      - '8000:8000'

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'

  celery:
    build: ./backend
    command: ["celery", "-A", "MHNU", "worker", "-B", "-l", "info"]
    depends_on:
      - redis
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=MHNU.settings.prod
      - TZ=America/Bogota
    volumes:
      - ./backend:/backend

volumes:
  postgres-data: