version: '3.7'
services:
  db:
    image: postgres:12-alpine
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  mhnu:
    build: ./src
    command: >
      sh -c "python manage.py wait_for_db && python manage.py runserver 0.0.0.0:9000"
    env_file: .env
    volumes:
      - ./src:/src
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=MHNU.settings.local

  nginx:
    image: nginx:alpine
    volumes:
      - ./src/static:/static
      - ./src/media:/media
      - ./nginx/local/dev.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"

    depends_on:
      - mhnu