# Generated by Django 3.2.6 on 2021-09-07 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0005_alter_slider_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
