# Generated by Django 3.2.9 on 2021-11-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0006_delete_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
