# Generated by Django 3.1.5 on 2021-02-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='geodetic_datum',
            field=models.CharField(blank=True, default='WGS84', max_length=255, null=True, verbose_name='geodetic datum'),
        ),
        migrations.AlterField(
            model_name='record',
            name='verbatim_coordinate_system',
            field=models.CharField(blank=True, choices=[('grados decimales', 'Decimal degrees'), ('grados minutos decimales', 'Degrees, decimal minutes'), ('grados minutos segundos', 'Degrees, minutes, seconds'), ('UTM', 'UTM'), ('CRTM', 'CRTM')], default='grados minutos segundos', max_length=50, null=True, verbose_name='verbatim coordinate system'),
        ),
    ]
