# Generated by Django 3.2.7 on 2021-09-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='enable',
        ),
        migrations.AddField(
            model_name='slider',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='enabled'),
        ),
    ]
